organization:
  name: test-overlay
  domain: devver.app
project:
  name: test-db
imagePullSecrets:
  - name: ghcr-secret
container:
  image: ghcr.io/devver-inc/deploy-agent:latest
  port: 80
  type: app
  command: []
  args: []
  env:
    DEVVER_SECRET: dev-secret-123
    NODE_ENV: production
    DEVVER_WIDGET_URL: >-
      https://cdn.jsdelivr.net/gh/Devver-Inc/overlay@dev/public/devver-overlay.iife.js
resources:
  requests:
    memory: 512Mi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 2000m
persistence:
  enabled: true
  app:
    size: 5Gi
    mountPath: /app
    storageClass: longhorn
  root:
    size: 5Gi
    mountPath: /root
    storageClass: longhorn
replicaCount: 1
ports:
  http: 80
  https: 443
labels: {}
annotations: {}
