namespace:
  create: false
organization:
  name: test-overlay
  domain: devver.app
project:
  name: test-db
auth:
  rootUsername: string
  rootPassword: string
replicaCount: 1
persistence:
  size: 10Gi
  storageClass: longhorn
resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 500m
