namespace:
  create: false
organization:
  name: lc8q7su06yeg-s-organization
  domain: devver.app
project:
  name: test-refacto
auth:
  rootUsername: string
  rootPassword: string
replicaCount: 1
persistence:
  size: 5Gi
  storageClass: nfs-devver-prod
resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 500m
